name: Build and deploy

env:
  BASE_DOMAIN: kb-dns.pages.dev
  BASE_PATH: /
  PAGES_PROJECT: kb-dns

on:
  push:
    branches: ["**"]
    tags:
      - v*
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
    outputs:
      branch: ${{ steps.get-branch.outputs.BRANCH_NAME }}
    runs-on: ubuntu-latest
    container:
      image: node:24
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Determine branch for deploy
        id: get-branch
        env:
          REF_NAME: ${{ github.ref_name }}
          EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          if [ "$REF_NAME" = "master" ]; then
            echo "BRANCH_NAME=main" >> $GITHUB_OUTPUT
          elif [ "$EVENT_NAME" = "pull_request" ]; then
            echo "BRANCH_NAME=pull-request-$PR_NUMBER" >> $GITHUB_OUTPUT
          else
            echo "BRANCH_NAME=$REF_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Run build
        run: |
          URL=https://${{ env.BASE_DOMAIN }} BASE_URL=${{ env.BASE_PATH }} pnpm build

          # Disable crawlers for preview builds.
          echo "User-Agent: *\nDisallow: /" > build/robots.txt

      - name: Upload build artifact
        if: github.event.pull_request.head.repo.fork == false
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: build/

  deploy:
    needs: build
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: build/

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy ./build --project-name="${{ env.PAGES_PROJECT }}" --branch "$BRANCH_NAME"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_WORKERS_ACCOUNT_ID }}
          BRANCH_NAME: ${{ needs.build.outputs.branch }}

      - name: Add comment to Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        env:
          BRANCH_NAME: ${{ needs.build.outputs.branch }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview was deployed to: https://${process.env.BRANCH_NAME}.${{ env.BASE_DOMAIN }}${{ env.BASE_PATH }}`
            })
