name: Sync with Crowdin

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Sync translations
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        run: pnpm run crowdin:sync

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: automatically update translations
          title: Update translations
          body: Transactions are synced from Crowdin
          reviewers: |
            el-termikael
            vbagirov
          branch: update-translations
          base: master
          delete-branch: true
