name: Sync with Crowdin

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: yarn install
        run: yarn install

      - name: sync translations
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        run: yarn run crowdin:sync

      - name: create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          commit-message: automatically update translations
          title: Update translations
          body: Transactions are synced from Crowdin
          reviewers: |
            el-termikael
            vbagirov
          branch: update-translations
          base: master
          delete-branch: true
